// src/components/ui/ProjectCard.svelte
<script lang="ts">
  import ArrowUpRight from 'lucide-svelte/icons/arrow-up-right';
  import Github from './icons/GithubIcon.svelte';
  
  export let project: any;
  export let locale: 'en' | 'es' = 'en';
  export let compact: boolean = false;
  export let t: any;
  
  // Tilt effect
  function handleTilt(e: MouseEvent) {
    if (compact) return;
    const card = e.currentTarget as HTMLElement;
    const rect = card.getBoundingClientRect();
    const x = ((e.clientX - rect.left) / rect.width - 0.5) * 10;
    const y = ((e.clientY - rect.top) / rect.height - 0.5) * -10;
    card.style.transform = `perspective(1000px) rotateX(${y}deg) rotateY(${x}deg) scale(1.02)`;
    card.style.borderColor = 'rgba(0,191,255,0.4)';
    card.style.boxShadow = '0 0 40px rgba(0,191,255,0.2), 0 20px 60px rgba(0,0,0,0.5)';
  }

  function resetTilt(e: MouseEvent) {
    if (compact) return;
    const card = e.currentTarget as HTMLElement;
    card.style.transform = 'perspective(1000px) rotateX(0) rotateY(0) scale(1)';
    card.style.borderColor = 'var(--c-border)';
    card.style.boxShadow = 'none';
  }
</script>

<div 
  class="relative overflow-hidden {compact ? 'p-5' : 'min-h-[420px] grid lg:grid-cols-[1.05fr_0.95fr] gap-0 p-0'}"
  on:mousemove={handleTilt}
  on:mouseleave={resetTilt}
  style="
    background: var(--c-surface);
    border: 1px solid var(--c-border);
    border-radius: 20px;
    transition: transform 0.1s ease, border-color 0.3s ease, box-shadow 0.3s ease;
    will-change: transform;
  "
>
  {#if !compact}
    <div aria-hidden="true" class="absolute inset-x-0 top-0 h-40 bg-gradient-to-b from-[rgba(0,191,255,0.15)] via-[rgba(0,191,255,0.05)] to-transparent" />
  {/if}
  
  <div class={compact ? "" : "flex flex-col p-6 sm:p-8 relative z-10"}>
    <div class="flex flex-wrap items-start justify-between gap-3">
      <div>
        <span style="font-family: 'Outfit', sans-serif; font-size:0.65rem; letter-spacing:0.2em; color:var(--c-fire); text-transform:uppercase">
          ✦ {project.type[locale]}
        </span>
        <h3 class="mt-3 text-white section-title {compact ? 'text-xl' : 'text-3xl'}">
          {project.name}
        </h3>
      </div>
      {#if project.status}
        <span style="
          background: rgba(0,191,255,0.08);
          border: 1px solid rgba(0,191,255,0.18);
          color: var(--c-fire);
          border-radius: 999px;
          padding: 0.25rem 0.75rem;
          font-family: 'Outfit', sans-serif;
          font-size: 0.65rem;
          font-weight: 700;
          letter-spacing: 0.1em;
          text-transform: uppercase;
        ">
          {project.status[locale]}
        </span>
      {/if}
    </div>
    
    <p class="mt-5 leading-7 text-white/70 {compact ? 'text-sm' : 'text-base'}">
      {project.description[locale]}
    </p>
    
    {#if project.impact}
      <p class="mt-5 border-l-2 pl-4 text-sm leading-7 text-white/80" style="border-color: var(--c-fire)">
        {project.impact[locale]}
      </p>
    {/if}
    
    {#if project.role}
      <p class="mt-5 text-xs font-mono font-semibold uppercase leading-6 tracking-[0.14em] text-white/50">
        {project.role[locale]}
      </p>
    {/if}
    
    <div class="mt-6 flex flex-wrap gap-2">
      {#each project.tags as tag}
        <span style="
          background: rgba(255,255,255,0.03);
          border: 1px solid rgba(255,255,255,0.1);
          color: rgba(255,255,255,0.7);
          border-radius: 4px;
          padding: 0.25rem 0.75rem;
          font-family: 'Outfit', sans-serif;
          font-size: 0.65rem;
          text-transform: uppercase;
        ">
          {tag}
        </span>
      {/each}
    </div>
    
    {#if !compact}
      <div class="mt-auto flex flex-wrap gap-4 pt-8">
        {#if project.github}
          <a href={project.github} target="_blank" rel="noreferrer" class="inline-flex min-h-11 items-center gap-2 rounded-full px-5 py-2.5 text-sm transition hover:scale-105" style="
            background: rgba(0,191,255,0.1);
            border: 1px solid rgba(0,191,255,0.3);
            color: var(--c-fire);
            font-family: 'Outfit', sans-serif;
            font-weight: 700;
            text-transform: uppercase;
          ">
            <Github size={16} /> GitHub
          </a>
        {/if}
        {#if project.demo}
          <a href={project.demo} target="_blank" rel="noreferrer" class="inline-flex min-h-11 items-center gap-2 rounded-full px-5 py-2.5 text-sm transition hover:scale-105" style="
            background: var(--c-fire);
            color: #000;
            font-family: 'Outfit', sans-serif;
            font-weight: 700;
            text-transform: uppercase;
            box-shadow: var(--glow-fire);
          ">
            {t.demo} <ArrowUpRight size={16} />
          </a>
        {/if}
      </div>
    {/if}
  </div>
  
  {#if !compact}
    <div class="hidden border-l relative p-6 lg:block" style="border-color: rgba(0,191,255,0.1); background: rgba(0,0,0,0.3)">
      <div class="relative h-full overflow-hidden rounded-xl border p-4 flex flex-col" style="
        border-color: rgba(0,191,255,0.2);
        background: rgba(0,0,0,0.5);
        box-shadow: inset 0 0 40px rgba(0,191,255,0.05);
      ">
        <div class="flex items-center justify-between border-b pb-3 mb-4" style="border-color: rgba(0,191,255,0.15)">
          <div class="flex gap-2" aria-hidden="true">
            <span class="h-2 w-2 rounded-full" style="background: var(--c-fire)"></span>
            <span class="h-2 w-2 rounded-full bg-white/40"></span>
            <span class="h-2 w-2 rounded-full bg-white/20"></span>
          </div>
          <span style="font-family: 'Outfit', sans-serif; font-size:0.55rem; letter-spacing:0.2em; color:var(--c-fire); text-transform:uppercase">
            SYS.DISPLAY
          </span>
        </div>
        
        {#if project.image?.src}
          <img 
            src={project.image.src} 
            alt={project.image.alt[locale]} 
            class="w-full rounded-lg border object-cover" 
            style="border-color: rgba(0,191,255,0.2)"
          />
        {:else}
          <div class="w-full flex-1 rounded-lg border flex items-center justify-center" style="
            border-color: rgba(0,191,255,0.15);
            background: rgba(0,191,255,0.03);
          ">
            <span style="font-family: 'Outfit', sans-serif; font-size:0.65rem; letter-spacing:0.2em; color:rgba(0,191,255,0.4); text-transform:uppercase">
              No Visual Data
            </span>
          </div>
        {/if}
        
        <div class="mt-4 grid grid-cols-3 gap-3">
          {#each (project.stack ?? project.tags).slice(0, 3) as item}
            <div class="rounded-lg border p-3 flex flex-col items-center text-center justify-center" style="
              border-color: rgba(0,191,255,0.15);
              background: rgba(0,191,255,0.03);
            ">
              <span style="font-family: 'Outfit', sans-serif; font-size:0.55rem; letter-spacing:0.1em; color:var(--c-fire); text-transform:uppercase" class="truncate w-full">
                {item}
              </span>
            </div>
          {/each}
        </div>
      </div>
    </div>
  {/if}
</div>

// _backup_components/ui/ProjectCard.tsx
import { ArrowUpRight, Github } from "lucide-react";
import { GlassCard } from "@/components/ui/GlassCard";
import { MediaImage } from "@/components/ui/MediaImage";
import type { Locale, Project } from "@/types";
import { cn } from "@/lib/utils";

type Props = {
  project: Project;
  locale: Locale;
  compact?: boolean;
  t: Record<string, string | string[]>;
};

export function ProjectCard({ project, locale, compact, t }: Props) {
  const accent = project.accent ?? "cyan";
  const accentClasses = {
    cyan: "from-cyan/26 via-cyan/8 to-transparent text-cyan",
    violet: "from-violet/26 via-violet/8 to-transparent text-violet-100",
    magenta: "from-magenta/24 via-magenta/8 to-transparent text-fuchsia-100"
  }[accent];

  return (
    <GlassCard className={compact ? "p-5" : "relative min-h-[420px] overflow-hidden p-0"}>
      {!compact ? <div aria-hidden className={cn("absolute inset-x-0 top-0 h-40 bg-gradient-to-b", accentClasses)} /> : null}
      <div className={cn("relative", compact ? "" : "grid min-h-[420px] gap-0 lg:grid-cols-[1.05fr_0.95fr]")}>
        <div className={compact ? "" : "flex flex-col p-6 sm:p-7"}>
          <div className="flex flex-wrap items-start justify-between gap-3">
            <div>
              <p className={cn("text-xs font-semibold uppercase text-cyan", compact ? "tracking-[0.12em]" : "tracking-[0.18em]")}>{project.type[locale]}</p>
              <h3 className={cn("mt-3 font-display font-semibold text-white", compact ? "text-xl" : "text-3xl")}>{project.name}</h3>
            </div>
            {project.status ? (
              <span className="rounded-full border border-white/10 bg-white/[0.06] px-3 py-1 text-xs font-semibold text-white/72">
                {project.status[locale]}
              </span>
            ) : null}
          </div>
          <p className={cn("mt-5 leading-7 text-white/68", compact ? "text-sm" : "text-base")}>{project.description[locale]}</p>
          {project.impact ? <p className="mt-5 border-l border-cyan/40 pl-4 text-sm leading-7 text-white/78">{project.impact[locale]}</p> : null}
          {project.role ? <p className="mt-5 text-xs font-semibold uppercase leading-6 tracking-[0.14em] text-white/44">{project.role[locale]}</p> : null}
          <div className="mt-6 flex flex-wrap gap-2">
            {project.tags.map((tag) => (
              <span key={tag} className="rounded-full bg-white/[0.055] px-3 py-1 text-xs text-white/64">
                {tag}
              </span>
            ))}
          </div>
          {!compact ? (
            <div className="mt-auto flex flex-wrap gap-3 pt-8">
              {project.github ? (
                <a href={project.github} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center gap-2 rounded-full bg-white px-4 py-2 text-sm font-semibold text-ink transition hover:bg-cyan focus:outline-none focus-visible:ring-2 focus-visible:ring-cyan">
                  <Github size={16} /> GitHub
                </a>
              ) : null}
              <a href="#contact" className="inline-flex min-h-11 items-center gap-2 rounded-full border border-white/10 px-4 py-2 text-sm font-semibold text-white/78 transition hover:border-cyan/40 hover:text-white focus:outline-none focus-visible:ring-2 focus-visible:ring-cyan">
                {String(t.demo)} <ArrowUpRight size={16} />
              </a>
              <a href="#contact" className="inline-flex min-h-11 items-center gap-2 rounded-full border border-white/10 px-4 py-2 text-sm font-semibold text-white/78 transition hover:border-violet/40 hover:text-white focus:outline-none focus-visible:ring-2 focus-visible:ring-cyan">
                {String(t.caseStudy)}
              </a>
            </div>
          ) : null}
        </div>
        {!compact ? (
          <>
          {project.image ? (
            <MediaImage
              src={project.image.src}
              alt={project.image.alt[locale]}
              className="mt-6 aspect-[16/9] rounded-2xl border border-white/10 lg:hidden"
            />
          ) : null}
          <div className="relative hidden border-l border-white/10 bg-ink/30 p-6 lg:block">
            <div className="project-screen relative h-full overflow-hidden rounded-2xl border border-white/10 bg-ink/78 p-4 shadow-2xl">
              <div className="flex items-center justify-between border-b border-white/10 pb-3">
                <div className="flex gap-1.5" aria-hidden>
                  <span className="h-2.5 w-2.5 rounded-full bg-magenta/80" />
                  <span className="h-2.5 w-2.5 rounded-full bg-cyan/80" />
                  <span className="h-2.5 w-2.5 rounded-full bg-violet/80" />
                </div>
                <span className="text-[10px] font-semibold uppercase text-white/38">Product system</span>
              </div>
              <div className="mt-5 grid gap-3">
                <MediaImage
                  src={project.image?.src}
                  alt={project.image?.alt[locale] ?? `${project.name} product preview`}
                  className="aspect-[16/10] rounded-xl border border-white/10"
                  imgClassName="object-cover"
                />
                <div className="grid grid-cols-3 gap-3">
                  {(project.stack ?? project.tags).slice(0, 3).map((item) => (
                    <div key={item} className="rounded-xl border border-white/10 bg-white/[0.04] p-3">
                      <div className="h-1.5 w-8 rounded-full bg-cyan/70" />
                      <p className="mt-3 text-[11px] font-medium leading-4 text-white/62">{item}</p>
                    </div>
                  ))}
                </div>
                <div className="mt-1 space-y-2">
                  {[78, 62, 88, 52].map((width) => (
                    <div key={width} className="h-2 rounded-full bg-white/[0.06]">
                      <div className="h-full rounded-full bg-gradient-to-r from-cyan/80 to-violet/70" style={{ width: `${width}%` }} />
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
          </>
        ) : null}
      </div>
    </GlassCard>
  );
}
