// _backup_components/sections/HeroSection.tsx
"use client";

import dynamic from "next/dynamic";
import { motion, useReducedMotion } from "framer-motion";
import { ArrowDown, Download, Mail } from "lucide-react";
import type { Locale } from "@/types";
import { MagneticButton } from "@/components/ui/MagneticButton";
import { TechOrbit } from "@/components/ui/TechOrbit";

const ThreeHeroObject = dynamic(() => import("@/components/ui/ThreeHeroObject").then((mod) => mod.ThreeHeroObject), {
  ssr: false,
  loading: () => <div className="h-[340px] w-full animate-pulse rounded-full bg-cyan/10 blur-2xl sm:h-[470px] lg:h-[580px]" />
});

const proofKeys = [
  ["heroMetricOne", "heroMetricOneLabel"],
  ["heroMetricTwo", "heroMetricTwoLabel"],
  ["heroMetricThree", "heroMetricThreeLabel"]
] as const;

export function HeroSection({ t }: { locale: Locale; t: Record<string, string | string[]> }) {
  const reduceMotion = useReducedMotion();

  return (
    <section id="home" className="relative z-10 flex min-h-[92svh] items-center px-5 pb-12 pt-28 sm:px-6 sm:pb-16 sm:pt-32">
      <div className="mx-auto grid w-full max-w-7xl items-center gap-8 lg:grid-cols-[minmax(0,1fr)_minmax(430px,0.86fr)] xl:gap-16">
        <motion.div initial={reduceMotion ? false : { opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.7 }}>
          <p className="max-w-2xl text-lg font-medium leading-8 text-white/72">
            Johan Gabriel Vasquez <span className="text-cyan">/</span> {String(t.heroSignal)}
          </p>
          <h1 className="mt-5 max-w-5xl font-display text-5xl font-semibold leading-[0.98] tracking-normal text-gradient sm:text-6xl lg:text-7xl xl:text-[5.7rem]">
            {String(t.heroTitle)}
          </h1>
          <p className="mt-7 max-w-2xl text-lg leading-8 text-white/70 sm:text-xl">{String(t.heroSubtitle)}</p>
          <div className="mt-9 flex flex-wrap gap-3" aria-label="Primary actions">
            <MagneticButton href="#projects">{String(t.viewProjects)}</MagneticButton>
            <MagneticButton href="#contact" variant="secondary"><Mail size={17} /> {String(t.contactMe)}</MagneticButton>
            <MagneticButton href="/Johan-Gabriel-Vasquez-CV.pdf" variant="ghost"><Download size={17} /> {String(t.downloadCv)}</MagneticButton>
          </div>
          <dl className="mt-10 grid max-w-2xl grid-cols-1 gap-3 border-y border-white/10 py-5 sm:grid-cols-3">
            {proofKeys.map(([valueKey, labelKey]) => (
              <div key={valueKey}>
                <dt className="font-display text-2xl font-semibold text-white">{String(t[valueKey])}</dt>
                <dd className="mt-1 text-sm leading-5 text-white/52">{String(t[labelKey])}</dd>
              </div>
            ))}
          </dl>
        </motion.div>

        <motion.div className="relative" initial={reduceMotion ? false : { opacity: 0, scale: 0.96 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 0.8, delay: 0.1 }}>
          <div className="hero-shell aurora-border glass relative overflow-hidden rounded-[1.5rem]">
            <div className="absolute inset-x-0 top-0 z-10 flex items-center justify-between border-b border-white/10 bg-ink/45 px-5 py-4 backdrop-blur">
              <p className="text-sm font-semibold text-white/80">{String(t.heroProof)}</p>
              <span className="h-2 w-2 rounded-full bg-cyan shadow-glow" />
            </div>
            <ThreeHeroObject />
            <TechOrbit />
            <div className="absolute inset-x-4 bottom-4 z-30 grid gap-2 rounded-2xl border border-white/10 bg-ink/72 p-3 backdrop-blur sm:grid-cols-3">
              {["UI system", "API layer", "Release path"].map((item) => (
                <div key={item} className="rounded-xl bg-white/[0.045] px-3 py-2">
                  <p className="text-[11px] font-semibold uppercase text-white/42">{item}</p>
                  <div className="mt-2 h-1.5 rounded-full bg-white/10">
                    <div className="h-full rounded-full bg-gradient-to-r from-cyan to-violet" style={{ width: item === "UI system" ? "92%" : item === "API layer" ? "84%" : "76%" }} />
                  </div>
                </div>
              ))}
            </div>
          </div>
        </motion.div>
      </div>
      <a href="#about" aria-label="Scroll to about" className="absolute bottom-8 left-1/2 hidden -translate-x-1/2 rounded-full border border-white/10 p-3 text-white/60 transition hover:text-cyan md:block">
        <ArrowDown size={18} />
      </a>
    </section>
  );
}

// src/components/sections/HeroSection.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { translations } from '../../../data/translations';
  import anime from 'animejs';
  import OrbitHeroObject from './OrbitHeroObject.svelte';

  export let locale: 'en' | 'es' = 'en';
  $: t = translations[locale];

  onMount(() => {

    // Split hero title into word spans for stagger
    const titleEl = document.querySelector('.hero-title') as HTMLElement;
    if (titleEl) {
      const words = titleEl.textContent!.trim().split(' ');
      titleEl.innerHTML = words.map(w => `<span class="hero-word inline-block max-w-full overflow-hidden py-2 -my-2"><span class="hero-word-inner inline-block max-w-full break-words">${w}</span></span>`).join(' ');

      // Title

      anime({
        targets: '.hero-word-inner',
        translateY: ['110%', '0%'],
        opacity: [0, 1],
        duration: 1100,
        delay: anime.stagger(80, { start: 300 }),
        easing: 'spring(1, 80, 10, 0)'
      });
    }

    // Subtitle
    anime({
      targets: '.hero-subtitle',
      opacity: [0, 1],
      translateY: [25, 0],
      duration: 800,
      delay: 800,
      easing: 'easeOutQuart'
    });

    // CTAs
    anime({
      targets: '.hero-cta',
      opacity: [0, 1],
      translateY: [20, 0],
      scale: [0.95, 1],
      duration: 700,
      delay: anime.stagger(100, { start: 1000 }),
      easing: 'spring(1, 80, 12, 0)'
    });

    // Metrics row
    anime({
      targets: '.hero-metric',
      opacity: [0, 1],
      translateY: [15, 0],
      duration: 600,
      delay: anime.stagger(80, { start: 1200 }),
      easing: 'easeOutQuart'
    });

    // Planet animation
    anime({
      targets: '.hero-planet',
      opacity: [0, 1],
      translateY: [40, 0],
      duration: 1000,
      delay: 1500,
      easing: 'easeOutQuart'
    });

    // Sparkle stars floating animation
    anime({
      targets: '.sparkle-star',
      translateY: [-6, 6],
      rotate: [0, 15],
      duration: 3000,
      loop: true,
      direction: 'alternate',
      delay: anime.stagger(400),
      easing: 'easeInOutSine'
    });
  });
</script>

<!-- Star decorators as SVG inline components -->
<svelte:head>
  <style>
    .sparkle-4pt {
      display: inline-block;
      clip-path: polygon(50% 0%, 55% 45%, 100% 50%, 55% 55%, 50% 100%, 45% 55%, 0% 50%, 45% 45%);
      background: var(--c-fire);
    }
  </style>
</svelte:head>

<section id="home" class="relative min-h-screen flex flex-col items-center justify-center pt-28 pb-20 overflow-hidden">

  <!-- Decorative sparkle stars (Y2K motif) -->
  <span class="sparkle-star absolute top-[18%] left-[8%] w-4 h-4 sparkle-4pt opacity-60" style="filter: drop-shadow(0 0 8px var(--c-fire))"></span>
  <span class="sparkle-star absolute top-[30%] right-[10%] w-3 h-3 sparkle-4pt opacity-40" style="filter: drop-shadow(0 0 6px var(--c-fire))"></span>
  <span class="sparkle-star absolute bottom-[25%] left-[15%] w-2 h-2 sparkle-4pt opacity-30"></span>
  <span class="sparkle-star absolute top-[60%] right-[6%] w-5 h-5 sparkle-4pt opacity-50" style="filter: drop-shadow(0 0 12px var(--c-fire))"></span>

  <div class="container mx-auto px-6 max-w-5xl relative z-10 text-center">

    <!-- Main title — word-by-word reveal -->
    <h1 class="hero-title text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-bold leading-[1.1] tracking-tight mb-8 mx-auto" style="
      font-family: 'Syncopate', sans-serif; font-weight: 700; text-transform: uppercase;
      color: var(--c-text); max-width: 100%; word-wrap: break-word;
    ">
      {t.heroTitle}
    </h1>

    <!-- Subtitle -->
    <p class="hero-subtitle max-w-2xl mx-auto text-base md:text-lg leading-relaxed mb-12 opacity-0" style="
      font-family: 'Outfit', sans-serif;
      color: var(--c-muted);
    ">
      {t.heroSubtitle}
    </p>

    <!-- CTAs -->
    <div class="flex flex-wrap items-center justify-center gap-4 mb-20">
      <a href="#projects" class="hero-cta opacity-0 px-8 py-4 rounded-full font-semibold text-black text-sm transition-transform hover:scale-105" style="
        font-family: 'Outfit', sans-serif;
        font-weight: 700;
        background: var(--c-fire);
        box-shadow: var(--glow-fire);
      ">
        {t.viewProjects}
        <svg class="inline ml-2 w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5">
          <path d="M5 12h14M12 5l7 7-7 7"/>
        </svg>
      </a>
      <a href="#contact" class="hero-cta opacity-0 px-8 py-4 rounded-full font-semibold text-sm transition-all hover:border-white/30" style="
        font-family: 'Outfit', sans-serif;
        font-weight: 700;
        color: var(--c-text);
        background: rgba(255,255,255,0.05);
        border: 1px solid rgba(255,255,255,0.12);
      ">
        {t.contactMe}
      </a>
      <a href="/Johan-Gabriel-Vasquez-CV.pdf" target="_blank" class="hero-cta opacity-0 px-8 py-4 rounded-full font-semibold text-sm transition-all hover:border-white/30 flex items-center gap-2" style="
        font-family: 'Outfit', sans-serif;
        font-weight: 700;
        color: var(--c-text);
        background: rgba(255,255,255,0.05);
        border: 1px solid rgba(255,255,255,0.12);
      ">
        <svg class="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4M7 10l5 5 5-5M12 15V3"/>
        </svg>
        {t.downloadCv}
      </a>
    </div>

    <!-- Metrics row -->
    <div class="grid grid-cols-3 gap-6 max-w-lg mx-auto pt-12 border-t mb-12" style="border-color: var(--c-border)">
      {#each [
        { val: t.heroMetricOne, label: t.heroMetricOneLabel },
        { val: t.heroMetricTwo, label: t.heroMetricTwoLabel },
        { val: t.heroMetricThree, label: t.heroMetricThreeLabel }
      ] as metric}
        <div class="hero-metric opacity-0 text-center">
          <div class="text-2xl font-bold mb-1" style="font-family: 'Syncopate', sans-serif; text-transform: uppercase; color: var(--c-fire)">
            {metric.val}
          </div>
          <div class="text-xs" style="font-family: 'Outfit', sans-serif; color:var(--c-muted); letter-spacing:0.08em; text-transform:uppercase">
            {metric.label}
          </div>
        </div>
      {/each}
    </div>

    <!-- Orbit Profile / Technologies -->
    <div class="hero-planet opacity-0 translate-y-8 relative z-0 mt-8 w-full">
      <OrbitHeroObject />
    </div>

  </div>

  <!-- Scroll indicator -->
  <div class="absolute bottom-8 left-1/2 -translate-x-1/2 flex flex-col items-center gap-2 opacity-50">
    <span style="font-family: 'Outfit', sans-serif; font-size:0.6rem; letter-spacing:0.2em; color:var(--c-muted)">SCROLL</span>
    <div class="w-px h-10 bg-gradient-to-b from-transparent to-current" style="color:var(--c-fire)"></div>
  </div>

</section>
