// src/components/layout/Footer.svelte
<script lang="ts">
  import Github from '../ui/icons/GithubIcon.svelte';
  import Linkedin from '../ui/icons/LinkedinIcon.svelte';
  import Mail from 'lucide-svelte/icons/mail';

  export let locale: 'en' | 'es' = 'en';
  
  const currentYear = new Date().getFullYear();
</script>

<footer class="relative z-10 px-5 py-12 sm:px-6 mt-10" style="
  background: var(--c-surface);
  border-top: 1px solid var(--c-border);
">
  <div class="mx-auto flex max-w-7xl flex-col items-center justify-between gap-6 sm:flex-row">
    <div class="flex items-center gap-3">
      <span class="flex h-8 w-8 items-center justify-center rounded-lg text-xs font-black" style="
        border: 1px solid rgba(0,191,255,0.4); 
        background: rgba(0,191,255,0.08); 
        color: var(--c-fire);
        font-family: 'Outfit', sans-serif;
      ">JG</span>
      <p style="font-family: 'Outfit', sans-serif; font-size:0.65rem; letter-spacing:0.1em; color:rgba(255,255,255,0.5); text-transform:uppercase">
        &copy; {currentYear} Johan Gabriel Vasquez
      </p>
    </div>
    
    <div class="flex items-center gap-6 text-white/50">
      <a href="https://github.com/Johanvasquezdev" target="_blank" rel="noreferrer" class="transition-colors hover:text-white" style="hover:color: var(--c-fire)" aria-label="GitHub">
        <Github size={20} />
      </a>
      <a href="https://www.linkedin.com/in/johan-gabriel-vasquez-5b539a312" target="_blank" rel="noreferrer" class="transition-colors hover:text-white" aria-label="LinkedIn">
        <Linkedin size={20} />
      </a>
      <a href="mailto:johanvasquezdev@gmail.com" class="transition-colors hover:text-white" aria-label="Email">
        <Mail size={20} />
      </a>
    </div>
  </div>
</footer>

// _backup_components/layout/Footer.tsx
export function Footer({ t }: { t: Record<string, string | string[]> }) {
  return (
    <footer className="relative z-10 border-t border-white/10 px-6 py-10">
      <div className="mx-auto flex max-w-7xl flex-col gap-4 text-sm text-white/55 md:flex-row md:items-center md:justify-between">
        <p>Copyright 2026 Johan Gabriel Vasquez. {String(t.footer)}</p>
        <div className="flex gap-4">
          <a href="mailto:johanvasquezdev@gmail.com" className="hover:text-cyan focus:outline-none focus-visible:ring-2 focus-visible:ring-cyan">
            Email
          </a>
          <a href="https://github.com/Johanvasquezdev" target="_blank" rel="noreferrer" className="hover:text-cyan focus:outline-none focus-visible:ring-2 focus-visible:ring-cyan">
            GitHub
          </a>
          <a href="https://www.linkedin.com/in/johan-gabriel-vasquez-5b539a312" target="_blank" rel="noreferrer" className="hover:text-cyan focus:outline-none focus-visible:ring-2 focus-visible:ring-cyan">
            LinkedIn
          </a>
        </div>
      </div>
    </footer>
  );
}
