// src/components/sections/ExperienceTimeline.svelte
<script lang="ts">
  import { experienceItems } from '../../../data/experience';
  import { translations } from '../../../data/translations';
  import SectionHeading from '../ui/SectionHeading.svelte';

  export let locale: 'en' | 'es' = 'en';
  $: t = translations[locale];
</script>

<section id="experience" class="relative z-10 px-5 sm:px-6">
  <div class="mx-auto max-w-7xl">
    <div class="anim-fade-up">
      <SectionHeading title={t.experienceTitle} subtitle={t.experienceSubtitle} />
    </div>
    
    <div class="relative mt-14 anim-stagger">
      <!-- Central Timeline line -->
      <div class="absolute left-4 top-0 h-full w-px md:left-1/2" style="background: linear-gradient(to bottom, rgba(0,191,255,0.8), rgba(0,191,255,0.1), transparent)"></div>
      
      <div class="grid gap-8">
        {#each experienceItems as item, index}
          <article class="relative md:grid md:grid-cols-2 md:gap-16 {index % 2 ? 'md:text-left' : 'md:text-right'}">
            <!-- Timeline node -->
            <span class="absolute left-4 top-7 flex h-6 w-6 -translate-x-1/2 items-center justify-center rounded-full md:left-1/2" style="
              background: rgba(3,5,10,1);
              border: 1px solid rgba(0,191,255,0.5);
              box-shadow: 0 0 15px rgba(0,191,255,0.5);
              transform: translateX(-50%);
            ">
              <span style="color: var(--c-fire); font-size: 0.6rem">✦</span>
            </span>
            
            <div class={index % 2 ? 'md:col-start-2' : ''}>
              <div class="ml-12 p-6 md:ml-0" style="
                background: var(--c-surface);
                border: 1px solid var(--c-border);
                border-radius: 16px;
                box-shadow: 0 10px 30px rgba(0,0,0,0.5);
                transition: border-color 0.3s ease;
              " on:mouseenter={(e) => e.currentTarget.style.borderColor = 'rgba(0,191,255,0.4)'} on:mouseleave={(e) => e.currentTarget.style.borderColor = 'var(--c-border)'}>
                <p style="font-family: 'Outfit', sans-serif; font-size:0.65rem; letter-spacing:0.2em; color:var(--c-fire); text-transform:uppercase">
                  SYS.LOG_0{index + 1}
                </p>
                <h3 class="mt-3 text-xl font-bold text-white display-type" style="text-transform: uppercase;">{item.title[locale]}</h3>
                <p class="mt-3 text-sm leading-7 text-white/70">{item.description[locale]}</p>
              </div>
            </div>
          </article>
        {/each}
      </div>
    </div>
  </div>
</section>

// _backup_components/sections/ExperienceTimeline.tsx
"use client";

import { motion } from "framer-motion";
import { experienceItems } from "@/data/experience";
import type { Locale } from "@/types";
import { SectionHeading } from "@/components/ui/SectionHeading";

export function ExperienceTimeline({ locale, t }: { locale: Locale; t: Record<string, string | string[]> }) {
  return (
    <section id="experience" className="relative z-10 px-5 py-20 sm:px-6 sm:py-24">
      <div className="mx-auto max-w-7xl">
        <SectionHeading title={String(t.experienceTitle)} subtitle={String(t.experienceSubtitle)} />
        <div className="relative mt-14">
          <div className="absolute left-4 top-0 h-full w-px bg-gradient-to-b from-cyan via-violet to-transparent md:left-1/2" />
          <div className="grid gap-7">
            {experienceItems.map((item, index) => (
              <motion.article
                key={item.title.en}
                className={`relative md:grid md:grid-cols-2 md:gap-16 ${index % 2 ? "md:text-left" : "md:text-right"}`}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
              >
                <span className="absolute left-4 top-7 h-4 w-4 -translate-x-1/2 rounded-full border border-cyan bg-ink shadow-glow md:left-1/2" />
                <div className={index % 2 ? "md:col-start-2" : ""}>
                  <div className="glass ml-10 rounded-2xl p-5 md:ml-0">
                    <p className="text-xs font-semibold uppercase tracking-[0.18em] text-cyan">0{index + 1}</p>
                    <h3 className="mt-3 font-display text-xl font-semibold text-white">{item.title[locale]}</h3>
                    <p className="mt-3 text-sm leading-7 text-white/65">{item.description[locale]}</p>
                  </div>
                </div>
              </motion.article>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}
